### ISSUE TITLE
Error when using unicode initialisation strings

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#28]
This is low-priority, sure, but it'll need to be fixed if we want Python 3 compatibility (as all strings are unicode by default in py3k). Unicode strings break a variety of constructors for quippy objects; for example, the following code:

``` python
from __future__ import unicode_literals
import quippy

pot = quippy.Potential('IP GAP', param_filename='../dimers/gp-merig-ljrep-2b.xml')
```

throws a `TypeError`, more specifically,

```
TypeError: No matching routine found in interface __init__
```

while replacing it with the following works fine:

``` python
pot = quippy.Potential(b'IP GAP', param_filename='../dimers/gp-merig-ljrep-2b.xml')
```

so it looks like filenames are unaffected.
The error does occur in param strings as well, though; the following again raises the error:

``` python
pot = quippy.Potential(b'IP LJ', param_str=u"""
<LJ_params n_types="1" label="default">
<per_type_data type="1" atomic_num="18" />
<per_pair_data type1="1" type2="1" sigma="4.0" eps6="1.0" eps12="1.0" cutoff="6.0" energy_shift="T" linear_force_shift="F" />
</LJ_params>""")
```

The simplest fix would be to convert all offending strings to `bytes` in Python 3, `str` in Python 2; there's some advice [here](http://python-future.org/what_else.html) on making it work in both so we don't have to maintain two separate codebases.

**Comment by max-veit** [comment]
After a bit more research, looks like we have to explicitly convert to bytes before passing it on to Fortran. (Python zen number 1: Explicit is better than implicit! -- see also https://snarky.ca/why-python-3-exists/)

**Comment by max-veit** [comment]
I'm guessing this is fixed by the move to Python 3...?

**Comment by jameskermode** [comment]
Not necessarily, I left this one open until testing as the strings still need to go from Python to FORTRAN, which still won’t like Unicode. Sure it’s fixable in the wrapper layer but needs testing.

**Comment by jameskermode** [comment]
But it is true that the example above somehow works!

**Comment by max-veit** [comment]
Hmmm... as long as the string doesn't contain any non-ASCII characters, then the UTF-8 encoding used by default (?) in Python should be identical to the ASCII encoding and there should be no problems. Of course, as soon as you try to use non-ASCII characters as identifiers, that's when the [mojibake](https://en.wikipedia.org/wiki/Mojibake) hits the fan.
